name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Start server
      run: npm run graphql-server
    - name: Start app
      run: npm run dev
    - name: Run Playwright login test
      run: npx playwright test login.spec.js
    - name: Run Playwright dashboard test
      run: npx playwright test dashboard.spec.js
    - name: Run Playwright mailing webkit test
      run: npx playwright test mailing.spec.js --project webkit
    - name: Run Playwright mailing firefox test
      run: npx playwright test mailing.spec.js --project firefox
    - name: Run Playwright mailing chromium test
      run: npx playwright test mailing.spec.js --project chromium
    - name: Run Playwright template webkit test
      run: npx playwright test template.spec.js --project webkit
    - name: Run Playwright template firefox test
      run: npx playwright test template.spec.js --project firefox
    - name: Run Playwright template chromium test
      run: npx playwright test template.spec.js --project chromium
